[package]
name = "skylink"
version = "0.1.0"
edition = "2018"
authors = ["Eric Mikulin"]
readme = "README.md"

[dependencies]
clap = { version = "2.33.1", features = ["yaml"] }
crossbeam = "0.7.3"
mavlink = { version = "0.8.5", features = ["ardupilotmega"] }