[package]
name = "skylink"
version = "0.1.0"
edition = "2018"
authors = ["Eric Mikulin"]
readme = "README.md"

[dependencies]
clap = "2.33.1"
mavlink = { version = "0.8.5", features = ["default", "ardupilotmega"] }